// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ6y6sj7Oxf5_3d-evX7KXymPUlwWovcs',
    appId: '1:975145454593:web:ef5fdc73727d169a6f8400',
    messagingSenderId: '975145454593',
    projectId: 'managementme-9e6a4',
    authDomain: 'managementme-9e6a4.firebaseapp.com',
    storageBucket: 'managementme-9e6a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbW9NJQNPHvWcdgZNIeFhTR-ObF7M-or0',
    appId: '1:975145454593:android:c406b26f240de72b6f8400',
    messagingSenderId: '975145454593',
    projectId: 'managementme-9e6a4',
    storageBucket: 'managementme-9e6a4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQNOZlZ0xFb_5_CMI3bi4JKSpOeIj9CKI',
    appId: '1:975145454593:ios:297e3a6c09898d266f8400',
    messagingSenderId: '975145454593',
    projectId: 'managementme-9e6a4',
    storageBucket: 'managementme-9e6a4.firebasestorage.app',
    iosBundleId: 'com.example.managementme',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQNOZlZ0xFb_5_CMI3bi4JKSpOeIj9CKI',
    appId: '1:975145454593:ios:297e3a6c09898d266f8400',
    messagingSenderId: '975145454593',
    projectId: 'managementme-9e6a4',
    storageBucket: 'managementme-9e6a4.firebasestorage.app',
    iosBundleId: 'com.example.managementme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ6y6sj7Oxf5_3d-evX7KXymPUlwWovcs',
    appId: '1:975145454593:web:727c90d98a9ff5d86f8400',
    messagingSenderId: '975145454593',
    projectId: 'managementme-9e6a4',
    authDomain: 'managementme-9e6a4.firebaseapp.com',
    storageBucket: 'managementme-9e6a4.firebasestorage.app',
  );
}
